
name: testemby789
on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: EmbyServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Emby Install
        run: |
          sudo apt-get -yqq install git lsb-release bc
          sudo git clone https://github.com/QuickBox/QB /etc/QuickBox
          sudo chmod +x /etc/QuickBox/setup/quickbox-setup
          sudo sh /etc/QuickBox/setup/quickbox-setup

