
name: testemby789
on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: EmbyServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Emby Install
        run: |
          apt-get -yqq update; apt-get -yqq upgrade; apt-get -yqq install git lsb-release bc; \
          git clone https://github.com/QuickBox/QB /etc/QuickBox; \
          sudo 'bash /etc/QuickBox/setup/quickbox-setup'
